### ISSUE TITLE
Shred not compatible with nocheatplus

### ISSUE THREAD

**Issue by Xardas88** [Zedly/Zenchantments#21]
Hi, the SHRED enchantment is not compatible with NoCheatPlus Anticheat.
It gives me this error when I break a block with an enchanted pickaxe  "'Player Name' might be using an AimBot (Check 3) (125VL)"
Can you hook zenchantment with nocheatplus/CompactNoCheatPlus pls? Thx for your work.

**Comment by Zedly** [comment]
Zenchantments emulates Bukkit events in order to comply with protection and logging plugins. NCP uses Bukkit events to measure the player's behavior. When you use Shred, Zenchantments quickly fires a number of BlockBreakEvents, which NCP interprets as a fast dig hack. Unfortunately there is no way to prevent this without interfacing directly with NCP
