### ISSUE TITLE
How plugin locales even work?

### ISSUE THREAD

**Issue by justjamesbond** [Zedly/Zenchantments#64]
I've noticed that the plugin's source resources include localization files for multiple languages. However, there doesn’t seem to be an obvious way to change the language in-game. I would like to know how to change/switch language of plugin?

**Comment by Geolykt** [comment]
The selected language depends on the locale of the JVM, as per https://github.com/Zedly/Zenchantments/blob/60bff12329e331f60af9d94c3ee40010d9bcc1d2/source/java/zedly/zenchantments/ZenchantmentsPlugin.java#L43

The language definitions themselves are hardcoded as per https://github.com/Zedly/Zenchantments/blob/60bff12329e331f60af9d94c3ee40010d9bcc1d2/source/java/zedly/zenchantments/I18n.java#L72 - that is, in order to change a string, the jar must be altered.

Note: It's been a very very long time since I worked with Zenchantments and my involvement predates the vast majority of the current codebase, so take my evaluation with a grain of salt.

**Comment by justjamesbond** [comment]
I need to recompile the plugin to I can change language?

**Comment by Geolykt** [comment]
You can change the language by changing the JVM startup flags - so something like `-Duser.language=es` to switch to Spanish. If you want to change the locale definitions themselves - then yeah, recompile it is.

**Comment by justjamesbond** [comment]
Alright, thank you
